/**
 * One-time cleanup: dedupe phantom activity rows generated by the
 * pre-fix sync/item route (which re-stamped every task as "updated"
 * on every full-vault sync pass).
 *
 * Strategy (Option A from the chat):
 *   - For every group of rows sharing the same (entity_id, action, summary),
 *     keep the MOST RECENT (by created_at DESC) and delete the rest.
 *   - Only operates on rows where entity_id IS NOT NULL — preserves
 *     activity entries that don't have an entity binding (org-level
 *     events, etc.).
 *   - Backs up the entire activity_feed table to
 *     activity_feed_bak_<timestamp> before deleting anything, so the
 *     operation is reversible.
 *
 * Use --dry-run to see counts without writing.
 *
 * Usage:
 *   set -a && source .env.local && set +a
 *   npm run dedupe:activity -- --dry-run
 *   npm run dedupe:activity
 */

import { sql } from "drizzle-orm";
import { db } from "../src/lib/db/client";

const DRY_RUN = process.argv.includes("--dry-run");

function ts(): string {
  return new Date().toISOString().replace(/[^\d]/g, "").slice(0, 14);
}

async function main() {
  console.log(DRY_RUN ? "[dry-run] " : "" + "deduping activity_feed...\n");

  // 1. Total row count before.
  const beforeRes = await db.execute<{ count: number }>(
    sql`SELECT count(*)::int AS count FROM activity_feed`,
  );
  const before = beforeRes.rows[0];
  console.log(`rows before: ${before.count}`);

  // 2. Identify how many rows would be deleted.
  const phantomRes = await db.execute<{ count: number }>(
    sql`
      WITH ranked AS (
        SELECT id,
               ROW_NUMBER() OVER (
                 PARTITION BY entity_id, action, summary
                 ORDER BY created_at DESC, id DESC
               ) AS rn
        FROM activity_feed
        WHERE entity_id IS NOT NULL
      )
      SELECT count(*)::int AS count FROM ranked WHERE rn > 1
    `,
  );
  const phantomCount = phantomRes.rows[0];
  console.log(`rows that would be deleted (phantom duplicates): ${phantomCount.count}`);
  console.log(`rows that would remain: ${before.count - phantomCount.count}\n`);

  if (DRY_RUN) {
    console.log("(dry-run — nothing modified)");
    return;
  }

  if (phantomCount.count === 0) {
    console.log("nothing to dedupe.");
    return;
  }

  // 3. Back up the table.
  const backupTable = `activity_feed_bak_${ts()}`;
  console.log(`backing up activity_feed → ${backupTable}`);
  await db.execute(
    sql.raw(`CREATE TABLE ${backupTable} AS SELECT * FROM activity_feed`),
  );
  console.log(`✓ backed up`);

  // 4. Delete the duplicates.
  console.log("deleting duplicates...");
  const deleteResult = await db.execute(
    sql`
      DELETE FROM activity_feed
      WHERE id IN (
        SELECT id FROM (
          SELECT id,
                 ROW_NUMBER() OVER (
                   PARTITION BY entity_id, action, summary
                   ORDER BY created_at DESC, id DESC
                 ) AS rn
          FROM activity_feed
          WHERE entity_id IS NOT NULL
        ) t
        WHERE t.rn > 1
      )
    `,
  );
  console.log(`✓ deleted (rowCount: ${deleteResult.rowCount ?? "?"})`);

  // 5. Final count.
  const afterRes = await db.execute<{ count: number }>(
    sql`SELECT count(*)::int AS count FROM activity_feed`,
  );
  const after = afterRes.rows[0];
  console.log(`\nrows after: ${after.count}`);
  console.log(`reduction: ${before.count - after.count} rows (${Math.round(((before.count - after.count) / before.count) * 100)}%)`);
  console.log(`\nbackup: ${backupTable}`);
  console.log(`to restore: TRUNCATE activity_feed; INSERT INTO activity_feed SELECT * FROM ${backupTable};`);
}

main().catch((err) => {
  console.error("dedupe failed:", err);
  process.exit(1);
});
