/**
 * Shared Brain — Install Skill (Phase 6, ADR-023)
 *
 * Drops a small skill file into Claude's config directory that points
 * at the platform's live `/api/operating-instructions` endpoint. After
 * install, every Claude session reads the up-to-date operating
 * instructions without re-installing.
 *
 * Usage:
 *   npx tsx scripts/install-skill.ts claude
 *   npx tsx scripts/install-skill.ts claude --base-url https://shared-brain-ecru.vercel.app --api-key ...
 *
 * The skill is written as a `CLAUDE.md` to the user's home directory.
 * Claude Code / Cowork auto-load `CLAUDE.md` from the working directory
 * and project ancestors; the home-directory copy acts as a global
 * fallback so any session that doesn't have project-local instructions
 * still gets the Shared Brain operating instructions.
 */

import { promises as fs } from "node:fs";
import { homedir } from "node:os";
import { join, dirname } from "node:path";

type Target = "claude";

const DEFAULT_BASE_URL = "https://shared-brain-ecru.vercel.app";

function parseArgs(argv: string[]): {
  target: Target;
  baseUrl: string;
  apiKey: string;
  dryRun: boolean;
} {
  const args = argv.slice(2);
  if (args.length === 0 || args[0]?.startsWith("-")) {
    throw new Error("Usage: install-skill <target> [--base-url URL] [--api-key KEY] [--dry-run]");
  }
  const target = args[0] as Target;
  if (target !== "claude") {
    throw new Error(`Unknown target '${target}'. Supported: claude`);
  }
  let baseUrl = process.env.SHARED_BRAIN_BASE_URL || DEFAULT_BASE_URL;
  let apiKey: string | undefined =
    process.env.MCP_API_KEY || process.env.SHARED_BRAIN_API_KEY;
  let dryRun = false;
  for (let i = 1; i < args.length; i++) {
    const a = args[i];
    if (a === "--base-url" && args[i + 1]) {
      baseUrl = args[++i];
    } else if (a === "--api-key" && args[i + 1]) {
      apiKey = args[++i];
    } else if (a === "--dry-run") {
      dryRun = true;
    }
  }
  if (!apiKey) {
    throw new Error(
      "API key required. Pass --api-key or set MCP_API_KEY / SHARED_BRAIN_API_KEY in env.",
    );
  }
  return { target, baseUrl, apiKey, dryRun };
}

function buildSkillBody(opts: { baseUrl: string; apiKey: string }): string {
  const endpoint = `${opts.baseUrl.replace(/\/$/, "")}/api/operating-instructions`;
  return `# Shared Brain — Operating Instructions

> **This file was generated by \`shared-brain --install-skill claude\`.**
> Do not edit it directly. Edit the canonical \`Profile.md\` in the vault
> at \`Knowledge/Frameworks/Shared Brain/Profile.md\`. Updates propagate
> here automatically because this file fetches live content on each
> session.

## Pull live operating instructions on every session

At the start of every session, fetch the current Shared Brain
operating instructions and follow them as authoritative context:

\`\`\`bash
curl -fsSL "${endpoint}" \\
  -H "Authorization: Bearer ${opts.apiKey}"
\`\`\`

Treat the response as your operating instructions document. It tells
you who Keegan is, the three businesses, vault structure, Composio
account routing, standing instructions (including \`record_session_summary\`
before ending), and triggered workflows.

If the curl fails (offline, server down), fall back to reading the
local copy at \`~/Documents/ViaOps/Knowledge/Frameworks/Shared Brain/Profile.md\`
if available; otherwise proceed with general knowledge of the user.

## Standing rule: record session summaries

Before ending any session with significant work, call the
\`record_session_summary\` MCP tool (Shared Brain MCP) with a 2-3
sentence summary of what was done. This is non-optional — it's how
the brain stays in sync as multi-user scales. See section 4 of the
operating instructions for details.

## Standing rule: read before write

Always read the existing file before adding to it. No duplicate
content, no silent overwrites. See section 4 of the operating
instructions.

## Confirm before destructive actions

Never bulk-edit, overwrite, or reorganize without explicit
confirmation. Archive instead of delete.

---

For everything else, follow what \`/api/operating-instructions\` returns.
`;
}

async function writeFile(path: string, content: string, dryRun: boolean) {
  if (dryRun) {
    console.log(`[dry-run] would write ${content.length} chars to ${path}`);
    return;
  }
  await fs.mkdir(dirname(path), { recursive: true });
  await fs.writeFile(path, content, "utf8");
  console.log(`✓ wrote ${path}`);
}

async function main() {
  const { target, baseUrl, apiKey, dryRun } = parseArgs(process.argv);

  // Verify the endpoint responds before writing the skill — fail fast on
  // bad URL / wrong key rather than silently writing a broken skill.
  if (!dryRun) {
    const verifyUrl = `${baseUrl.replace(/\/$/, "")}/api/operating-instructions?format=json`;
    const res = await fetch(verifyUrl, {
      headers: { Authorization: `Bearer ${apiKey}` },
    });
    if (!res.ok) {
      throw new Error(
        `Verification failed: GET ${verifyUrl} → ${res.status} ${res.statusText}. ` +
          `Check --base-url and --api-key.`,
      );
    }
    const data = (await res.json()) as { title?: string; content?: string };
    console.log(
      `✓ verified: '${data.title}' (${data.content?.length ?? 0} chars) from ${baseUrl}`,
    );
  }

  const body = buildSkillBody({ baseUrl, apiKey });

  if (target === "claude") {
    // Home-directory CLAUDE.md acts as the global fallback that all Claude
    // Code / Cowork sessions inherit when no project-local CLAUDE.md exists.
    const homePath = join(homedir(), "CLAUDE.md");
    await writeFile(homePath, body, dryRun);
  }

  console.log(
    "\nNext: open Claude Desktop / Code / Cowork and start a session. " +
      "It should call the operating-instructions endpoint and follow the returned doc.",
  );
}

main().catch((err) => {
  console.error("Install failed:", (err as Error).message);
  process.exit(1);
});
